export const EASTER_EGGS = [
  {
    id: 'gasparilla',
    lat: 27.938,
    lng: -82.465,
    minZoom: 13,
    maxZoom: 18,
    size: [28, 20],
    title: 'Gasparilla!',
    fact: "Tampa's Gasparilla Pirate Festival has celebrated José Gaspar since 1904. The invasion flotilla is the third-largest parade in the US.",
    svgKey: 'pirateShip',
  },
  {
    id: 'kraken',
    lat: 27.60,
    lng: -83.10,
    minZoom: 11,
    maxZoom: 14,
    size: [32, 22],
    title: 'Release the Kraken!',
    fact: 'The Gulf of Mexico reaches depths of over 14,383 feet at the Sigsbee Deep. Who knows what lurks below...',
    svgKey: 'kraken',
  },
  {
    id: 'manatee',
    lat: 27.78,
    lng: -82.42,
    minZoom: 14,
    maxZoom: 18,
    size: [24, 16],
    title: 'Sea Cow Spotted!',
    fact: 'The TECO Manatee Viewing Center in Apollo Beach attracts hundreds of manatees each winter, drawn by warm power plant discharge water.',
    svgKey: 'manatee',
  },
  {
    id: 'skunkApe',
    lat: 27.12,
    lng: -82.22,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 24],
    title: 'Skunk Ape Sighting!',
    fact: "Florida's Skunk Ape — a smelly, swamp-dwelling cousin of Bigfoot — has been \"spotted\" in the Myakka region since the 1960s.",
    svgKey: 'skunkApe',
  },
  {
    id: 'strawberry',
    lat: 28.015,
    lng: -82.12,
    minZoom: 13,
    maxZoom: 18,
    size: [16, 20],
    title: 'Berry Nice!',
    fact: 'Plant City is the Winter Strawberry Capital of the World, producing 75% of the US winter strawberry crop.',
    svgKey: 'strawberry',
  },
  {
    id: 'meltingClock',
    lat: 27.766,
    lng: -82.631,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 20],
    title: 'The Persistence of Memory',
    fact: "The Dalí Museum in St. Petersburg houses the largest collection of Salvador Dalí's work outside Europe, including over 2,400 objects.",
    svgKey: 'meltingClock',
  },
  {
    id: 'lightning',
    lat: 27.943,
    lng: -82.452,
    minZoom: 14,
    maxZoom: 18,
    size: [14, 24],
    title: 'Lightning Capital!',
    fact: 'Tampa Bay is the lightning capital of the US, averaging 90+ lightning days per year. Amalie Arena is home to the Tampa Bay Lightning.',
    svgKey: 'lightning',
  },
  {
    id: 'mermaid',
    lat: 28.52,
    lng: -82.57,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 24],
    title: 'Weeki Wachee Mermaids!',
    fact: "Weeki Wachee Springs has featured live \"mermaid\" shows since 1947, making it one of Florida's oldest roadside attractions.",
    svgKey: 'mermaid',
  },
  {
    id: 'cigar',
    lat: 27.962,
    lng: -82.438,
    minZoom: 15,
    maxZoom: 18,
    size: [28, 10],
    title: 'Cigar City!',
    fact: 'By the early 1900s, Ybor City was producing over 700 million hand-rolled cigars per year, earning Tampa the title "Cigar Capital of the World."',
    svgKey: 'cigar',
  },
  // --- Batch 1: Wildlife & Nature ---
  {
    id: 'dolphin',
    lat: 27.62,
    lng: -82.60,
    minZoom: 14,
    maxZoom: 18,
    size: [24, 16],
    title: 'Bottlenose!',
    fact: 'Tampa Bay is home to over 500 resident bottlenose dolphins. They are frequently spotted near the Sunshine Skyway, bow-riding alongside boats.',
    svgKey: 'dolphin',
  },
  {
    id: 'pelican',
    lat: 27.69,
    lng: -82.74,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 22],
    title: 'Brown Pelican!',
    fact: 'Once nearly wiped out by DDT, the brown pelican made a remarkable comeback and is now a ubiquitous sight on Gulf Coast piers and jetties.',
    svgKey: 'pelican',
  },
  {
    id: 'osprey',
    lat: 27.20,
    lng: -82.48,
    minZoom: 14,
    maxZoom: 18,
    size: [22, 22],
    title: 'Osprey!',
    fact: "There's literally a town called Osprey south of Sarasota. These fish hawks build massive nests on channel markers and power poles across the region.",
    svgKey: 'osprey',
  },
  {
    id: 'sandhillCrane',
    lat: 27.84,
    lng: -82.28,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 24],
    title: 'Sandhill Crane!',
    fact: 'Florida sandhill cranes are a non-migratory subspecies. In Riverview and Lithia, they casually stroll through subdivisions and hold up traffic.',
    svgKey: 'sandhillCrane',
  },
  {
    id: 'gopherTortoise',
    lat: 28.48,
    lng: -82.38,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 16],
    title: 'Gopher Tortoise!',
    fact: "Florida's state tortoise is a keystone species — its burrows shelter over 350 other species. They're protected and common in the sandy scrub near Brooksville.",
    svgKey: 'gopherTortoise',
  },
  {
    id: 'alligator',
    lat: 27.24,
    lng: -82.30,
    minZoom: 14,
    maxZoom: 18,
    size: [26, 14],
    title: 'Gator!',
    fact: 'Myakka River State Park is one of the best places in Florida to see wild alligators. The park is home to an estimated 100+ gators.',
    svgKey: 'alligator',
  },
  {
    id: 'roseateSpoonbill',
    lat: 27.58,
    lng: -82.56,
    minZoom: 15,
    maxZoom: 18,
    size: [20, 22],
    title: 'Roseate Spoonbill!',
    fact: 'Often mistaken for flamingos, roseate spoonbills are native to Florida and feed by sweeping their spoon-shaped bills through shallow mangrove waters.',
    svgKey: 'roseateSpoonbill',
  },
  {
    id: 'seaTurtle',
    lat: 27.53,
    lng: -82.73,
    minZoom: 14,
    maxZoom: 18,
    size: [22, 18],
    title: 'Sea Turtle Nesting!',
    fact: 'Anna Maria Island beaches are major loggerhead sea turtle nesting grounds. From May to October, thousands of hatchlings make their dash to the Gulf.',
    svgKey: 'seaTurtle',
  },
  // --- Batch 2: Landmarks & Sports ---
  {
    id: 'skywayBridge',
    lat: 27.615,
    lng: -82.655,
    minZoom: 12,
    maxZoom: 18,
    size: [30, 16],
    title: 'Sunshine Skyway!',
    fact: 'The Sunshine Skyway Bridge spans 4.1 miles across Tampa Bay. The iconic cable-stayed design was completed in 1987, replacing the original bridge after a tragic ship collision in 1980.',
    svgKey: 'skywayBridge',
  },
  {
    id: 'donCesar',
    lat: 27.725,
    lng: -82.74,
    minZoom: 15,
    maxZoom: 18,
    size: [18, 20],
    title: 'The Pink Palace!',
    fact: 'The Don CeSar opened in 1928 and has hosted F. Scott Fitzgerald, Al Capone, and countless celebrities. It served as a VA hospital during WWII before being restored to its pink glory.',
    svgKey: 'donCesar',
  },
  {
    id: 'ringlingCircus',
    lat: 27.326,
    lng: -82.551,
    minZoom: 14,
    maxZoom: 18,
    size: [22, 20],
    title: 'Greatest Show on Earth!',
    fact: "Sarasota was the winter home of Ringling Brothers circus from 1927 to 1960. John Ringling's legacy includes the stunning Ringling Museum and Ca' d'Zan mansion.",
    svgKey: 'ringlingCircus',
  },
  {
    id: 'spongeDiver',
    lat: 28.15,
    lng: -82.76,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 24],
    title: 'Sponge Diver!',
    fact: 'Greek immigrants made Tarpon Springs the sponge capital of the US in the early 1900s. Divers still harvest natural sponges from the Gulf using traditional methods.',
    svgKey: 'spongeDiver',
  },
  {
    id: 'hockeyPuck',
    lat: 27.950,
    lng: -82.460,
    minZoom: 15,
    maxZoom: 18,
    size: [14, 14],
    title: 'Back-to-Back!',
    fact: 'The Tampa Bay Lightning won back-to-back Stanley Cups in 2020 and 2021. Tampa became a true hockey town despite the tropical climate.',
    svgKey: 'hockeyPuck',
  },
  {
    id: 'pirateFlag',
    lat: 27.976,
    lng: -82.503,
    minZoom: 15,
    maxZoom: 18,
    size: [18, 14],
    title: 'Fire the Cannons!',
    fact: 'Raymond James Stadium features a 103-foot pirate ship that fires cannons after every Buccaneers touchdown. The Bucs won Super Bowl LV at home in 2021.',
    svgKey: 'pirateFlag',
  },
  {
    id: 'stingray',
    lat: 27.768,
    lng: -82.653,
    minZoom: 15,
    maxZoom: 18,
    size: [20, 18],
    title: 'Rays Up!',
    fact: "The Tampa Bay Rays played in Tropicana Field — the last indoor MLB stadium — since 1998. Known for doing more with less, they've been perennial contenders.",
    svgKey: 'stingray',
  },
  {
    id: 'flamencoDancer',
    lat: 27.958,
    lng: -82.445,
    minZoom: 15,
    maxZoom: 18,
    size: [16, 22],
    title: 'Olé!',
    fact: "The Columbia Restaurant in Ybor City, opened in 1905, is Florida's oldest restaurant. Its flamenco shows and Spanish-Cuban cuisine celebrate the neighborhood's heritage.",
    svgKey: 'flamencoDancer',
  },
  {
    id: 'greekCross',
    lat: 28.17,
    lng: -82.75,
    minZoom: 15,
    maxZoom: 18,
    size: [16, 16],
    title: 'Epiphany Cross Dive!',
    fact: "Tarpon Springs hosts the world-famous Epiphany cross dive every January 6th. Young men dive into Spring Bayou to retrieve a cross — a tradition since 1906. It's the largest Greek community in the US.",
    svgKey: 'greekCross',
  },
];
