export const EASTER_EGGS = [
  {
    id: 'gasparilla',
    lat: 27.938,
    lng: -82.465,
    minZoom: 11,
    maxZoom: 18,
    size: [42, 30],
    title: 'Gasparilla!',
    fact: "Tampa's Gasparilla Pirate Festival has celebrated José Gaspar since 1904. The invasion flotilla is the third-largest parade in the US.",
    svgKey: 'pirateShip',
    animCategory: 'heritage',
  },
  {
    id: 'kraken',
    lat: 27.62,
    lng: -82.82,
    minZoom: 10,
    maxZoom: 16,
    size: [54, 38],
    title: 'Release the Kraken!',
    fact: 'The Gulf of Mexico reaches depths of over 14,383 feet at the Sigsbee Deep. Who knows what lurks below...',
    svgKey: 'kraken',
    animCategory: 'folklore',
  },
  {
    id: 'skunkApe',
    lat: 27.12,
    lng: -82.22,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 38],
    title: 'Skunk Ape Sighting!',
    fact: "Florida's Skunk Ape — a smelly, swamp-dwelling cousin of Bigfoot — has been \"spotted\" in the Myakka region since the 1960s.",
    svgKey: 'skunkApe',
    animCategory: 'folklore',
  },
  {
    id: 'strawberry',
    lat: 28.015,
    lng: -82.12,
    minZoom: 11,
    maxZoom: 18,
    size: [26, 32],
    title: 'Berry Nice!',
    fact: 'Plant City is the Winter Strawberry Capital of the World, producing 75% of the US winter strawberry crop.',
    svgKey: 'strawberry',
    animCategory: 'culture',
  },
  {
    id: 'lightning',
    lat: 27.943,
    lng: -82.452,
    minZoom: 11,
    maxZoom: 18,
    size: [22, 38],
    title: 'Lightning Capital!',
    fact: 'Tampa Bay is the lightning capital of the US, averaging 90+ lightning days per year. Amalie Arena is home to the Tampa Bay Lightning.',
    svgKey: 'lightning',
    animCategory: 'nature',
  },
  {
    id: 'mermaid',
    lat: 28.52,
    lng: -82.57,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 38],
    title: 'Weeki Wachee Mermaids!',
    fact: "Weeki Wachee Springs has featured live \"mermaid\" shows since 1947, making it one of Florida's oldest roadside attractions.",
    svgKey: 'mermaid',
    animCategory: 'folklore',
  },
  {
    id: 'cigar',
    lat: 27.962,
    lng: -82.438,
    minZoom: 12,
    maxZoom: 18,
    size: [42, 16],
    title: 'Cigar City!',
    fact: 'By the early 1900s, Ybor City was producing over 700 million hand-rolled cigars per year, earning Tampa the title "Cigar Capital of the World."',
    svgKey: 'cigar',
    animCategory: 'culture',
  },
  // --- Batch 1: Wildlife & Nature ---
  {
    id: 'dolphin',
    lat: 27.62,
    lng: -82.60,
    minZoom: 11,
    maxZoom: 18,
    size: [38, 26],
    title: 'Bottlenose!',
    fact: 'Tampa Bay is home to over 500 resident bottlenose dolphins. They are frequently spotted near the Sunshine Skyway, bow-riding alongside boats.',
    svgKey: 'dolphin',
    animCategory: 'marine',
  },
  {
    id: 'pelican',
    lat: 27.69,
    lng: -82.74,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 34],
    title: 'Brown Pelican!',
    fact: 'Once nearly wiped out by DDT, the brown pelican made a remarkable comeback and is now a ubiquitous sight on Gulf Coast piers and jetties.',
    svgKey: 'pelican',
    animCategory: 'birds',
  },
  {
    id: 'osprey',
    lat: 27.20,
    lng: -82.48,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 34],
    title: 'Osprey!',
    fact: "There's literally a town called Osprey south of Sarasota. These fish hawks build massive nests on channel markers and power poles across the region.",
    svgKey: 'osprey',
    animCategory: 'birds',
  },
  {
    id: 'sandhillCrane',
    lat: 27.84,
    lng: -82.28,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 38],
    title: 'Sandhill Crane!',
    fact: 'Florida sandhill cranes are a non-migratory subspecies. In Riverview and Lithia, they casually stroll through subdivisions and hold up traffic.',
    svgKey: 'sandhillCrane',
    animCategory: 'birds',
  },
  {
    id: 'gopherTortoise',
    lat: 28.48,
    lng: -82.38,
    minZoom: 11,
    maxZoom: 18,
    size: [32, 26],
    title: 'Gopher Tortoise!',
    fact: "Florida's state tortoise is a keystone species — its burrows shelter over 350 other species. They're protected and common in the sandy scrub near Brooksville.",
    svgKey: 'gopherTortoise',
    animCategory: 'landmarks',
  },
  {
    id: 'alligator',
    lat: 27.24,
    lng: -82.30,
    minZoom: 11,
    maxZoom: 18,
    size: [40, 22],
    title: 'Gator!',
    fact: 'Myakka River State Park is one of the best places in Florida to see wild alligators. The park is home to an estimated 100+ gators.',
    svgKey: 'alligator',
    animCategory: 'marine',
  },
  {
    id: 'roseateSpoonbill',
    lat: 27.58,
    lng: -82.56,
    minZoom: 12,
    maxZoom: 18,
    size: [32, 34],
    title: 'Roseate Spoonbill!',
    fact: 'Often mistaken for flamingos, roseate spoonbills are native to Florida and feed by sweeping their spoon-shaped bills through shallow mangrove waters.',
    svgKey: 'roseateSpoonbill',
    animCategory: 'birds',
  },
  {
    id: 'seaTurtle',
    lat: 27.53,
    lng: -82.73,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 28],
    title: 'Sea Turtle Nesting!',
    fact: 'Anna Maria Island beaches are major loggerhead sea turtle nesting grounds. From May to October, thousands of hatchlings make their dash to the Gulf.',
    svgKey: 'seaTurtle',
    animCategory: 'marine',
  },
  // --- Batch 2: Landmarks & Sports ---
  {
    id: 'skywayBridge',
    lat: 27.615,
    lng: -82.655,
    minZoom: 10,
    maxZoom: 18,
    size: [48, 26],
    title: 'Sunshine Skyway!',
    fact: 'The Sunshine Skyway Bridge spans 4.1 miles across Tampa Bay. The iconic cable-stayed design was completed in 1987, replacing the original bridge after a tragic ship collision in 1980.',
    svgKey: 'skywayBridge',
    animCategory: 'landmarks',
  },
  {
    id: 'spongeDiver',
    lat: 28.15,
    lng: -82.76,
    minZoom: 11,
    maxZoom: 18,
    size: [26, 38],
    title: 'Sponge Diver!',
    fact: 'Greek immigrants made Tarpon Springs the sponge capital of the US in the early 1900s. Divers still harvest natural sponges from the Gulf using traditional methods.',
    svgKey: 'spongeDiver',
    animCategory: 'heritage',
  },
  {
    id: 'hockeyPuck',
    lat: 27.950,
    lng: -82.460,
    minZoom: 12,
    maxZoom: 18,
    size: [22, 22],
    title: 'Back-to-Back!',
    fact: 'The Tampa Bay Lightning won back-to-back Stanley Cups in 2020 and 2021. Tampa became a true hockey town despite the tropical climate.',
    svgKey: 'hockeyPuck',
    animCategory: 'sports',
  },
  {
    id: 'pirateFlag',
    lat: 27.976,
    lng: -82.503,
    minZoom: 12,
    maxZoom: 18,
    size: [28, 22],
    title: 'Fire the Cannons!',
    fact: 'Raymond James Stadium features a 103-foot pirate ship that fires cannons after every Buccaneers touchdown. The Bucs won Super Bowl LV at home in 2021.',
    svgKey: 'pirateFlag',
    animCategory: 'sports',
  },
  {
    id: 'stingray',
    lat: 27.768,
    lng: -82.653,
    minZoom: 12,
    maxZoom: 18,
    size: [32, 28],
    title: 'Rays Up!',
    fact: "The Tampa Bay Rays played in Tropicana Field — the last indoor MLB stadium — since 1998. Known for doing more with less, they've been perennial contenders.",
    svgKey: 'stingray',
    animCategory: 'marine',
  },
  {
    id: 'greekCross',
    lat: 28.17,
    lng: -82.75,
    minZoom: 12,
    maxZoom: 18,
    size: [26, 26],
    title: 'Epiphany Cross Dive!',
    fact: "Tarpon Springs hosts the world-famous Epiphany cross dive every January 6th. Young men dive into Spring Bayou to retrieve a cross — a tradition since 1906. It's the largest Greek community in the US.",
    svgKey: 'greekCross',
    animCategory: 'heritage',
  },
  // --- Batch 3: Food & History ---
  {
    id: 'cubanSandwich',
    lat: 27.995,
    lng: -82.48,
    minZoom: 12,
    maxZoom: 18,
    size: [38, 20],
    title: 'Tampa Cuban!',
    fact: 'Tampa — not Miami — claims the original Cuban sandwich. The addition of Genoa salami reflects the Italian immigrants of Ybor City who worked alongside Cuban cigar makers.',
    svgKey: 'cubanSandwich',
    animCategory: 'culture',
  },
  {
    id: 'grouper',
    lat: 27.79,
    lng: -82.78,
    minZoom: 12,
    maxZoom: 18,
    size: [34, 22],
    title: 'Grouper Sandwich!',
    fact: "The grouper sandwich is THE Gulf Coast dish. John's Pass Village in Madeira Beach is ground zero for the best ones — fresh, never frozen, blackened or fried.",
    svgKey: 'grouper',
    animCategory: 'marine',
  },
  {
    id: 'orange',
    lat: 27.96,
    lng: -81.95,
    minZoom: 11,
    maxZoom: 18,
    size: [26, 26],
    title: 'Florida Orange!',
    fact: 'Polk County was the heart of the Florida citrus belt. Before freezes and development, the region produced a huge share of the world\'s orange juice.',
    svgKey: 'orange',
    animCategory: 'culture',
  },
  {
    id: 'craftBeer',
    lat: 27.775,
    lng: -82.68,
    minZoom: 12,
    maxZoom: 18,
    size: [22, 28],
    title: 'Cheers!',
    fact: "Tampa Bay's craft beer scene is nationally ranked. Cigar City Brewing's Jai Alai IPA put the region on the map, and dozens of breweries have followed.",
    svgKey: 'craftBeer',
    animCategory: 'culture',
  },
  {
    id: 'flamingo',
    lat: 27.88,
    lng: -82.72,
    minZoom: 12,
    maxZoom: 18,
    size: [22, 34],
    title: 'Lawn Flamingo!',
    fact: 'The plastic pink flamingo was invented in 1957 by Don Featherstone. It became the ultimate symbol of Florida kitsch and was named the official city bird of Madison, WI.',
    svgKey: 'flamingo',
    animCategory: 'birds',
  },
  {
    id: 'tikiHut',
    lat: 27.46,
    lng: -82.70,
    minZoom: 12,
    maxZoom: 18,
    size: [28, 28],
    title: 'Tiki Time!',
    fact: "Florida's tiki bar culture thrives along the Gulf Coast. From waterfront dives to upscale resorts, the thatched-roof tiki hut is an essential part of the coastal experience.",
    svgKey: 'tikiHut',
    animCategory: 'landmarks',
  },
  // --- Batch 4: Quirky & Deep Cuts ---
  {
    id: 'ufo',
    lat: 27.35,
    lng: -82.18,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 22],
    title: 'UFO Sighting!',
    fact: 'Florida consistently ranks among the top states for UFO sightings. The rural areas east of Tampa Bay have had numerous reported encounters over the decades.',
    svgKey: 'ufo',
    animCategory: 'folklore',
  },
  {
    id: 'conchShell',
    lat: 26.95,
    lng: -82.35,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 28],
    title: 'Conch Shell!',
    fact: 'The Gulf Coast beaches near Englewood and Boca Grande are prime shelling territory. Queen conchs, once abundant, are now protected — but their shells still wash ashore.',
    svgKey: 'conchShell',
    animCategory: 'landmarks',
  },
  {
    id: 'treasureChest',
    lat: 26.75,
    lng: -82.26,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 26],
    title: 'Pirate Treasure!',
    fact: "Gasparilla Island (Boca Grande) is named after the legendary pirate José Gaspar. Whether he was real or myth, locals still dream of finding his buried treasure.",
    svgKey: 'treasureChest',
    animCategory: 'heritage',
  },
  {
    id: 'gibsonton',
    lat: 27.85,
    lng: -82.38,
    minZoom: 12,
    maxZoom: 18,
    size: [32, 28],
    title: 'Gibtown Showtown!',
    fact: '"Gibtown" was THE winter home for carnival and sideshow performers from the 1940s-80s. The post office had a special low counter for little people. Lobster Boy lived here.',
    svgKey: 'gibsonton',
    animCategory: 'folklore',
  },
  {
    id: 'spookHill',
    lat: 27.90,
    lng: -81.59,
    minZoom: 12,
    maxZoom: 18,
    size: [28, 22],
    title: 'Spook Hill!',
    fact: "Lake Wales' Spook Hill is a famous gravity hill where cars appear to roll uphill. Legend attributes it to a Native American chief battling a giant alligator.",
    svgKey: 'spookHill',
    animCategory: 'folklore',
  },
  {
    id: 'joyland',
    lat: 27.48,
    lng: -82.55,
    minZoom: 12,
    maxZoom: 18,
    size: [32, 32],
    title: 'Joyland!',
    fact: 'The abandoned Joyland amusement park in Bradenton has achieved urban legend status. Its rusting rides and overgrown grounds have become a haunting local landmark.',
    svgKey: 'joyland',
    animCategory: 'folklore',
  },
  {
    id: 'babeRuth',
    lat: 28.02,
    lng: -82.15,
    minZoom: 12,
    maxZoom: 18,
    size: [26, 26],
    title: 'The Bambino!',
    fact: 'Plant City hosted Babe Ruth-era spring training. The Bambino himself practiced on these fields, part of Florida\'s deep baseball spring training tradition.',
    svgKey: 'babeRuth',
    animCategory: 'sports',
  },
  {
    id: 'phosphateMining',
    lat: 27.90,
    lng: -81.88,
    minZoom: 11,
    maxZoom: 18,
    size: [32, 26],
    title: 'Bone Valley!',
    fact: 'Polk County\'s "Bone Valley" produces 75% of US phosphate and 25% of the world\'s supply. The mining has also unearthed incredible fossils, including prehistoric sharks and mastodons.',
    svgKey: 'phosphateMining',
    animCategory: 'heritage',
  },
  // --- Batch 5: Deep Cuts & Gap Fillers ---
  {
    id: 'sharkTooth',
    lat: 27.10,
    lng: -82.45,
    minZoom: 11,
    maxZoom: 18,
    size: [22, 28],
    title: 'Shark Tooth Capital!',
    fact: 'Venice Beach is the "Shark Tooth Capital of the World." Fossilized teeth from prehistoric megalodon and other sharks wash up constantly, some millions of years old.',
    svgKey: 'sharkTooth',
    animCategory: 'marine',
  },
  {
    id: 'tarponFish',
    lat: 26.72,
    lng: -82.25,
    minZoom: 11,
    maxZoom: 18,
    size: [38, 26],
    title: 'Silver King!',
    fact: 'Boca Grande Pass is the tarpon fishing capital of the world. Every spring, massive "Silver Kings" up to 200 lbs pour through the pass, drawing anglers from across the globe.',
    svgKey: 'tarponFish',
    animCategory: 'marine',
  },
  {
    id: 'shipwreck',
    lat: 27.35,
    lng: -82.90,
    minZoom: 10,
    maxZoom: 16,
    size: [38, 26],
    title: 'Shipwreck!',
    fact: 'Hundreds of shipwrecks lie on the Gulf floor off the Tampa Bay coast. From Spanish galleons to WWII-era vessels, these wrecks create artificial reefs teeming with marine life.',
    svgKey: 'shipwreck',
    animCategory: 'folklore',
  },
  {
    id: 'mantaRay',
    lat: 27.40,
    lng: -82.70,
    minZoom: 11,
    maxZoom: 18,
    size: [38, 28],
    title: 'Manta Ray!',
    fact: 'Spotted eagle rays and mantas frequent the warm Gulf waters near Longboat Key. Their graceful underwater "flight" makes them a favorite sight for divers and snorkelers.',
    svgKey: 'mantaRay',
    animCategory: 'marine',
  },
  {
    id: 'spanishMoss',
    lat: 28.00,
    lng: -82.44,
    minZoom: 12,
    maxZoom: 18,
    size: [26, 34],
    title: 'Spanish Moss!',
    fact: "Spanish moss isn't moss at all — it's an epiphyte related to pineapples. Draped on every live oak in old Seminole Heights, it defines the Gothic beauty of Florida's tree canopy.",
    svgKey: 'spanishMoss',
    animCategory: 'heritage',
  },
  {
    id: 'greenFlash',
    lat: 27.50,
    lng: -82.85,
    minZoom: 11,
    maxZoom: 18,
    size: [32, 22],
    title: 'Green Flash!',
    fact: "At sunset over the Gulf, a rare green flash can appear for 1–2 seconds as the sun dips below the horizon. Caused by atmospheric refraction, it's a bucket-list sighting for sunset watchers.",
    svgKey: 'greenFlash',
    animCategory: 'nature',
  },
  {
    id: 'unconquered',
    lat: 27.15,
    lng: -82.05,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 34],
    title: 'Unconquered!',
    fact: "The Seminole Tribe of Florida never signed a peace treaty with the US government. They call themselves 'The Unconquered People,' descendants of those who resisted forced removal.",
    svgKey: 'unconquered',
    animCategory: 'heritage',
  },
  {
    id: 'mangroveTunnels',
    lat: 27.70,
    lng: -82.58,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 26],
    title: 'Mangrove Tunnel!',
    fact: "Tampa Bay's mangrove tunnels are a kayaker's paradise. These tangled root systems serve as nurseries for 75% of the bay's commercial fish species.",
    svgKey: 'mangroveTunnels',
    animCategory: 'nature',
  },
  {
    id: 'kerouac',
    lat: 27.77,
    lng: -82.64,
    minZoom: 11,
    maxZoom: 18,
    size: [26, 28],
    title: 'On the Road!',
    fact: 'Beat Generation icon Jack Kerouac spent his final years in St. Petersburg. He wrote and drank at local haunts before passing away here in 1969 at age 47.',
    svgKey: 'kerouac',
    animCategory: 'heritage',
  },
  {
    id: 'bioluminescence',
    lat: 27.42,
    lng: -82.68,
    minZoom: 11,
    maxZoom: 18,
    size: [32, 22],
    title: 'Bioluminescence!',
    fact: 'On warm summer nights, certain Tampa Bay waters glow with bioluminescent dinoflagellates. Every paddle stroke lights up electric blue-green.',
    svgKey: 'bioluminescence',
    animCategory: 'nature',
  },
  {
    id: 'floridaMan',
    lat: 28.05,
    lng: -82.40,
    minZoom: 11,
    maxZoom: 18,
    size: [28, 28],
    title: 'Florida Man!',
    fact: "The 'Florida Man' meme exists because Florida's Sunshine Law makes arrest records easily accessible to journalists — creating an endless supply of bizarre headlines from every county.",
    svgKey: 'floridaMan',
    animCategory: 'landmarks',
  },
  {
    id: 'hurricaneAlley',
    lat: 27.60,
    lng: -83.05,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 28],
    title: 'Hurricane Alley!',
    fact: "Tampa Bay hasn't taken a direct hit from a major hurricane since 1921, yet it's considered the most vulnerable metro in the US for catastrophic storm surge.",
    svgKey: 'hurricaneAlley',
    animCategory: 'nature',
  },
  {
    id: 'redTide',
    lat: 27.30,
    lng: -82.75,
    minZoom: 11,
    maxZoom: 18,
    size: [32, 22],
    title: 'Red Tide!',
    fact: 'The Karenia brevis algal bloom has struck the Gulf Coast for centuries — Spanish explorers documented fish kills in the 1500s. The natural toxin causes respiratory irritation on beaches.',
    svgKey: 'redTide',
    animCategory: 'nature',
  },
  {
    id: 'honeymoonIsland',
    lat: 28.07,
    lng: -82.83,
    minZoom: 11,
    maxZoom: 18,
    size: [34, 26],
    title: 'Honeymoon Island!',
    fact: "Originally called Hog Island, it was renamed in 1939 when a developer gave newlyweds free honeymoon trips. A hurricane later split it in two, creating Caladesi Island next door.",
    svgKey: 'honeymoonIsland',
    animCategory: 'landmarks',
  },
  {
    id: 'ghostOrchid',
    lat: 27.05,
    lng: -81.95,
    minZoom: 11,
    maxZoom: 18,
    size: [26, 32],
    title: 'Ghost Orchid!',
    fact: "Florida's rare ghost orchid, made famous by 'The Orchid Thief,' blooms in deep swamps. The leafless epiphyte appears to float in mid-air — ethereal and almost impossible to find.",
    svgKey: 'ghostOrchid',
    animCategory: 'nature',
  },
];
