export const EASTER_EGGS = [
  {
    id: 'gasparilla',
    lat: 27.938,
    lng: -82.465,
    minZoom: 12,
    maxZoom: 18,
    size: [28, 20],
    title: 'Gasparilla!',
    fact: "Tampa's Gasparilla Pirate Festival has celebrated José Gaspar since 1904. The invasion flotilla is the third-largest parade in the US.",
    svgKey: 'pirateShip',
    animCategory: 'culture',
  },
  {
    id: 'kraken',
    lat: 27.60,
    lng: -83.10,
    minZoom: 10,
    maxZoom: 14,
    size: [32, 22],
    title: 'Release the Kraken!',
    fact: 'The Gulf of Mexico reaches depths of over 14,383 feet at the Sigsbee Deep. Who knows what lurks below...',
    svgKey: 'kraken',
    animCategory: 'water',
  },
  {
    id: 'manatee',
    lat: 27.78,
    lng: -82.42,
    minZoom: 13,
    maxZoom: 18,
    size: [24, 16],
    title: 'Sea Cow Spotted!',
    fact: 'The TECO Manatee Viewing Center in Apollo Beach attracts hundreds of manatees each winter, drawn by warm power plant discharge water.',
    svgKey: 'manatee',
    animCategory: 'water',
  },
  {
    id: 'skunkApe',
    lat: 27.12,
    lng: -82.22,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 24],
    title: 'Skunk Ape Sighting!',
    fact: "Florida's Skunk Ape — a smelly, swamp-dwelling cousin of Bigfoot — has been \"spotted\" in the Myakka region since the 1960s.",
    svgKey: 'skunkApe',
    animCategory: 'land',
  },
  {
    id: 'strawberry',
    lat: 28.015,
    lng: -82.12,
    minZoom: 12,
    maxZoom: 18,
    size: [16, 20],
    title: 'Berry Nice!',
    fact: 'Plant City is the Winter Strawberry Capital of the World, producing 75% of the US winter strawberry crop.',
    svgKey: 'strawberry',
    animCategory: 'food',
  },
  {
    id: 'meltingClock',
    lat: 27.766,
    lng: -82.631,
    minZoom: 13,
    maxZoom: 18,
    size: [20, 20],
    title: 'The Persistence of Memory',
    fact: "The Dalí Museum in St. Petersburg houses the largest collection of Salvador Dalí's work outside Europe, including over 2,400 objects.",
    svgKey: 'meltingClock',
    animCategory: 'culture',
  },
  {
    id: 'lightning',
    lat: 27.943,
    lng: -82.452,
    minZoom: 13,
    maxZoom: 18,
    size: [14, 24],
    title: 'Lightning Capital!',
    fact: 'Tampa Bay is the lightning capital of the US, averaging 90+ lightning days per year. Amalie Arena is home to the Tampa Bay Lightning.',
    svgKey: 'lightning',
    animCategory: 'culture',
  },
  {
    id: 'mermaid',
    lat: 28.52,
    lng: -82.57,
    minZoom: 12,
    maxZoom: 18,
    size: [18, 24],
    title: 'Weeki Wachee Mermaids!',
    fact: "Weeki Wachee Springs has featured live \"mermaid\" shows since 1947, making it one of Florida's oldest roadside attractions.",
    svgKey: 'mermaid',
    animCategory: 'culture',
  },
  {
    id: 'cigar',
    lat: 27.962,
    lng: -82.438,
    minZoom: 14,
    maxZoom: 18,
    size: [28, 10],
    title: 'Cigar City!',
    fact: 'By the early 1900s, Ybor City was producing over 700 million hand-rolled cigars per year, earning Tampa the title "Cigar Capital of the World."',
    svgKey: 'cigar',
    animCategory: 'food',
  },
  // --- Batch 1: Wildlife & Nature ---
  {
    id: 'dolphin',
    lat: 27.62,
    lng: -82.60,
    minZoom: 13,
    maxZoom: 18,
    size: [24, 16],
    title: 'Bottlenose!',
    fact: 'Tampa Bay is home to over 500 resident bottlenose dolphins. They are frequently spotted near the Sunshine Skyway, bow-riding alongside boats.',
    svgKey: 'dolphin',
    animCategory: 'water',
  },
  {
    id: 'pelican',
    lat: 27.69,
    lng: -82.74,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 22],
    title: 'Brown Pelican!',
    fact: 'Once nearly wiped out by DDT, the brown pelican made a remarkable comeback and is now a ubiquitous sight on Gulf Coast piers and jetties.',
    svgKey: 'pelican',
    animCategory: 'bird',
  },
  {
    id: 'osprey',
    lat: 27.20,
    lng: -82.48,
    minZoom: 13,
    maxZoom: 18,
    size: [22, 22],
    title: 'Osprey!',
    fact: "There's literally a town called Osprey south of Sarasota. These fish hawks build massive nests on channel markers and power poles across the region.",
    svgKey: 'osprey',
    animCategory: 'bird',
  },
  {
    id: 'sandhillCrane',
    lat: 27.84,
    lng: -82.28,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 24],
    title: 'Sandhill Crane!',
    fact: 'Florida sandhill cranes are a non-migratory subspecies. In Riverview and Lithia, they casually stroll through subdivisions and hold up traffic.',
    svgKey: 'sandhillCrane',
    animCategory: 'bird',
  },
  {
    id: 'gopherTortoise',
    lat: 28.48,
    lng: -82.38,
    minZoom: 13,
    maxZoom: 18,
    size: [20, 16],
    title: 'Gopher Tortoise!',
    fact: "Florida's state tortoise is a keystone species — its burrows shelter over 350 other species. They're protected and common in the sandy scrub near Brooksville.",
    svgKey: 'gopherTortoise',
    animCategory: 'land',
  },
  {
    id: 'alligator',
    lat: 27.24,
    lng: -82.30,
    minZoom: 13,
    maxZoom: 18,
    size: [26, 14],
    title: 'Gator!',
    fact: 'Myakka River State Park is one of the best places in Florida to see wild alligators. The park is home to an estimated 100+ gators.',
    svgKey: 'alligator',
    animCategory: 'land',
  },
  {
    id: 'roseateSpoonbill',
    lat: 27.58,
    lng: -82.56,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 22],
    title: 'Roseate Spoonbill!',
    fact: 'Often mistaken for flamingos, roseate spoonbills are native to Florida and feed by sweeping their spoon-shaped bills through shallow mangrove waters.',
    svgKey: 'roseateSpoonbill',
    animCategory: 'bird',
  },
  {
    id: 'seaTurtle',
    lat: 27.53,
    lng: -82.73,
    minZoom: 13,
    maxZoom: 18,
    size: [22, 18],
    title: 'Sea Turtle Nesting!',
    fact: 'Anna Maria Island beaches are major loggerhead sea turtle nesting grounds. From May to October, thousands of hatchlings make their dash to the Gulf.',
    svgKey: 'seaTurtle',
    animCategory: 'water',
  },
  // --- Batch 2: Landmarks & Sports ---
  {
    id: 'skywayBridge',
    lat: 27.615,
    lng: -82.655,
    minZoom: 11,
    maxZoom: 18,
    size: [30, 16],
    title: 'Sunshine Skyway!',
    fact: 'The Sunshine Skyway Bridge spans 4.1 miles across Tampa Bay. The iconic cable-stayed design was completed in 1987, replacing the original bridge after a tragic ship collision in 1980.',
    svgKey: 'skywayBridge',
    animCategory: 'landmark',
  },
  {
    id: 'donCesar',
    lat: 27.725,
    lng: -82.74,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 20],
    title: 'The Pink Palace!',
    fact: 'The Don CeSar opened in 1928 and has hosted F. Scott Fitzgerald, Al Capone, and countless celebrities. It served as a VA hospital during WWII before being restored to its pink glory.',
    svgKey: 'donCesar',
    animCategory: 'landmark',
  },
  {
    id: 'ringlingCircus',
    lat: 27.326,
    lng: -82.551,
    minZoom: 13,
    maxZoom: 18,
    size: [22, 20],
    title: 'Greatest Show on Earth!',
    fact: "Sarasota was the winter home of Ringling Brothers circus from 1927 to 1960. John Ringling's legacy includes the stunning Ringling Museum and Ca' d'Zan mansion.",
    svgKey: 'ringlingCircus',
    animCategory: 'landmark',
  },
  {
    id: 'spongeDiver',
    lat: 28.15,
    lng: -82.76,
    minZoom: 13,
    maxZoom: 18,
    size: [16, 24],
    title: 'Sponge Diver!',
    fact: 'Greek immigrants made Tarpon Springs the sponge capital of the US in the early 1900s. Divers still harvest natural sponges from the Gulf using traditional methods.',
    svgKey: 'spongeDiver',
    animCategory: 'water',
  },
  {
    id: 'hockeyPuck',
    lat: 27.950,
    lng: -82.460,
    minZoom: 14,
    maxZoom: 18,
    size: [14, 14],
    title: 'Back-to-Back!',
    fact: 'The Tampa Bay Lightning won back-to-back Stanley Cups in 2020 and 2021. Tampa became a true hockey town despite the tropical climate.',
    svgKey: 'hockeyPuck',
    animCategory: 'sport',
  },
  {
    id: 'pirateFlag',
    lat: 27.976,
    lng: -82.503,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 14],
    title: 'Fire the Cannons!',
    fact: 'Raymond James Stadium features a 103-foot pirate ship that fires cannons after every Buccaneers touchdown. The Bucs won Super Bowl LV at home in 2021.',
    svgKey: 'pirateFlag',
    animCategory: 'sport',
  },
  {
    id: 'stingray',
    lat: 27.768,
    lng: -82.653,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 18],
    title: 'Rays Up!',
    fact: "The Tampa Bay Rays played in Tropicana Field — the last indoor MLB stadium — since 1998. Known for doing more with less, they've been perennial contenders.",
    svgKey: 'stingray',
    animCategory: 'water',
  },
  {
    id: 'flamencoDancer',
    lat: 27.958,
    lng: -82.445,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 22],
    title: 'Olé!',
    fact: "The Columbia Restaurant in Ybor City, opened in 1905, is Florida's oldest restaurant. Its flamenco shows and Spanish-Cuban cuisine celebrate the neighborhood's heritage.",
    svgKey: 'flamencoDancer',
    animCategory: 'culture',
  },
  {
    id: 'greekCross',
    lat: 28.17,
    lng: -82.75,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 16],
    title: 'Epiphany Cross Dive!',
    fact: "Tarpon Springs hosts the world-famous Epiphany cross dive every January 6th. Young men dive into Spring Bayou to retrieve a cross — a tradition since 1906. It's the largest Greek community in the US.",
    svgKey: 'greekCross',
    animCategory: 'culture',
  },
  // --- Batch 3: Food & History ---
  {
    id: 'cubanSandwich',
    lat: 27.995,
    lng: -82.48,
    minZoom: 14,
    maxZoom: 18,
    size: [24, 12],
    title: 'Tampa Cuban!',
    fact: 'Tampa — not Miami — claims the original Cuban sandwich. The addition of Genoa salami reflects the Italian immigrants of Ybor City who worked alongside Cuban cigar makers.',
    svgKey: 'cubanSandwich',
    animCategory: 'food',
  },
  {
    id: 'grouper',
    lat: 27.79,
    lng: -82.78,
    minZoom: 14,
    maxZoom: 18,
    size: [22, 14],
    title: 'Grouper Sandwich!',
    fact: "The grouper sandwich is THE Gulf Coast dish. John's Pass Village in Madeira Beach is ground zero for the best ones — fresh, never frozen, blackened or fried.",
    svgKey: 'grouper',
    animCategory: 'food',
  },
  {
    id: 'orange',
    lat: 27.96,
    lng: -81.95,
    minZoom: 12,
    maxZoom: 18,
    size: [16, 16],
    title: 'Florida Orange!',
    fact: 'Polk County was the heart of the Florida citrus belt. Before freezes and development, the region produced a huge share of the world\'s orange juice.',
    svgKey: 'orange',
    animCategory: 'food',
  },
  {
    id: 'craftBeer',
    lat: 27.775,
    lng: -82.68,
    minZoom: 14,
    maxZoom: 18,
    size: [14, 18],
    title: 'Cheers!',
    fact: "Tampa Bay's craft beer scene is nationally ranked. Cigar City Brewing's Jai Alai IPA put the region on the map, and dozens of breweries have followed.",
    svgKey: 'craftBeer',
    animCategory: 'food',
  },
  {
    id: 'flamingo',
    lat: 27.88,
    lng: -82.72,
    minZoom: 14,
    maxZoom: 18,
    size: [14, 22],
    title: 'Lawn Flamingo!',
    fact: 'The plastic pink flamingo was invented in 1957 by Don Featherstone. It became the ultimate symbol of Florida kitsch and was named the official city bird of Madison, WI.',
    svgKey: 'flamingo',
    animCategory: 'bird',
  },
  {
    id: 'galleonAnchor',
    lat: 27.52,
    lng: -82.63,
    minZoom: 13,
    maxZoom: 18,
    size: [16, 22],
    title: 'De Soto Landed Here!',
    fact: 'Hernando de Soto landed near here in 1539 with 600+ men, beginning the first major European exploration of the American Southeast. The De Soto National Memorial marks the spot.',
    svgKey: 'galleonAnchor',
    animCategory: 'landmark',
  },
  {
    id: 'shuffleboard',
    lat: 27.77,
    lng: -82.645,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 14],
    title: 'Shuffle On!',
    fact: "The St. Petersburg Shuffleboard Club, founded in 1924, is the world's oldest and largest. It has 65 courts and helped define St. Pete's reputation as a retirement paradise.",
    svgKey: 'shuffleboard',
    animCategory: 'culture',
  },
  {
    id: 'tikiHut',
    lat: 27.46,
    lng: -82.70,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 18],
    title: 'Tiki Time!',
    fact: "Florida's tiki bar culture thrives along the Gulf Coast. From waterfront dives to upscale resorts, the thatched-roof tiki hut is an essential part of the coastal experience.",
    svgKey: 'tikiHut',
    animCategory: 'culture',
  },
  // --- Batch 4: Quirky & Deep Cuts ---
  {
    id: 'ufo',
    lat: 27.35,
    lng: -82.18,
    minZoom: 13,
    maxZoom: 18,
    size: [22, 14],
    title: 'UFO Sighting!',
    fact: 'Florida consistently ranks among the top states for UFO sightings. The rural areas east of Tampa Bay have had numerous reported encounters over the decades.',
    svgKey: 'ufo',
    animCategory: 'spooky',
  },
  {
    id: 'conchShell',
    lat: 26.95,
    lng: -82.35,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 18],
    title: 'Conch Shell!',
    fact: 'The Gulf Coast beaches near Englewood and Boca Grande are prime shelling territory. Queen conchs, once abundant, are now protected — but their shells still wash ashore.',
    svgKey: 'conchShell',
    animCategory: 'culture',
  },
  {
    id: 'treasureChest',
    lat: 26.75,
    lng: -82.26,
    minZoom: 13,
    maxZoom: 18,
    size: [18, 16],
    title: 'Pirate Treasure!',
    fact: "Gasparilla Island (Boca Grande) is named after the legendary pirate José Gaspar. Whether he was real or myth, locals still dream of finding his buried treasure.",
    svgKey: 'treasureChest',
    animCategory: 'culture',
  },
  {
    id: 'gibsonton',
    lat: 27.85,
    lng: -82.38,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 18],
    title: 'Gibtown Showtown!',
    fact: '"Gibtown" was THE winter home for carnival and sideshow performers from the 1940s-80s. The post office had a special low counter for little people. Lobster Boy lived here.',
    svgKey: 'gibsonton',
    animCategory: 'spooky',
  },
  {
    id: 'spookHill',
    lat: 27.90,
    lng: -81.59,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 14],
    title: 'Spook Hill!',
    fact: "Lake Wales' Spook Hill is a famous gravity hill where cars appear to roll uphill. Legend attributes it to a Native American chief battling a giant alligator.",
    svgKey: 'spookHill',
    animCategory: 'spooky',
  },
  {
    id: 'joyland',
    lat: 27.48,
    lng: -82.55,
    minZoom: 14,
    maxZoom: 18,
    size: [20, 20],
    title: 'Joyland!',
    fact: 'The abandoned Joyland amusement park in Bradenton has achieved urban legend status. Its rusting rides and overgrown grounds have become a haunting local landmark.',
    svgKey: 'joyland',
    animCategory: 'spooky',
  },
  {
    id: 'babeRuth',
    lat: 28.02,
    lng: -82.15,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 16],
    title: 'The Bambino!',
    fact: 'Plant City hosted Babe Ruth-era spring training. The Bambino himself practiced on these fields, part of Florida\'s deep baseball spring training tradition.',
    svgKey: 'babeRuth',
    animCategory: 'sport',
  },
  {
    id: 'phosphateMining',
    lat: 27.90,
    lng: -81.88,
    minZoom: 13,
    maxZoom: 18,
    size: [20, 16],
    title: 'Bone Valley!',
    fact: 'Polk County\'s "Bone Valley" produces 75% of US phosphate and 25% of the world\'s supply. The mining has also unearthed incredible fossils, including prehistoric sharks and mastodons.',
    svgKey: 'phosphateMining',
    animCategory: 'culture',
  },
  // --- Batch 5: Deep Cuts & Gap Fillers ---
  {
    id: 'solomonsCastle',
    lat: 27.05,
    lng: -81.92,
    minZoom: 14,
    maxZoom: 18,
    size: [18, 20],
    title: "Solomon's Castle!",
    fact: "Howard Solomon built an entire castle out of discarded newspaper printing plates in Ona, FL. The folk art masterpiece gleams in the sun and houses his sculptures and inventions.",
    svgKey: 'solomonsCastle',
    animCategory: 'landmark',
  },
  {
    id: 'weedonIsland',
    lat: 27.85,
    lng: -82.60,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 18],
    title: 'Ancient Mound!',
    fact: 'Weedon Island Preserve in St. Pete contains Native American mound sites dating back 10,000+ years. The Weedon Island archaeological culture influenced pottery styles across the Southeast.',
    svgKey: 'weedonIsland',
    animCategory: 'landmark',
  },
  {
    id: 'bernsSteak',
    lat: 27.925,
    lng: -82.49,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 14],
    title: "Bern's!",
    fact: "Bern's Steak House on South Howard has one of the world's largest wine collections (over 500,000 bottles) and a legendary upstairs dessert room with private booths.",
    svgKey: 'bernsSteak',
    animCategory: 'food',
  },
  {
    id: 'sharkTooth',
    lat: 27.10,
    lng: -82.45,
    minZoom: 13,
    maxZoom: 18,
    size: [14, 18],
    title: 'Shark Tooth Capital!',
    fact: 'Venice Beach is the "Shark Tooth Capital of the World." Fossilized teeth from prehistoric megalodon and other sharks wash up constantly, some millions of years old.',
    svgKey: 'sharkTooth',
    animCategory: 'water',
  },
  {
    id: 'tarponFish',
    lat: 26.72,
    lng: -82.25,
    minZoom: 13,
    maxZoom: 18,
    size: [24, 16],
    title: 'Silver King!',
    fact: 'Boca Grande Pass is the tarpon fishing capital of the world. Every spring, massive "Silver Kings" up to 200 lbs pour through the pass, drawing anglers from across the globe.',
    svgKey: 'tarponFish',
    animCategory: 'water',
  },
  {
    id: 'shipwreck',
    lat: 27.35,
    lng: -82.90,
    minZoom: 11,
    maxZoom: 16,
    size: [24, 16],
    title: 'Shipwreck!',
    fact: 'Hundreds of shipwrecks lie on the Gulf floor off the Tampa Bay coast. From Spanish galleons to WWII-era vessels, these wrecks create artificial reefs teeming with marine life.',
    svgKey: 'shipwreck',
    animCategory: 'spooky',
  },
  {
    id: 'mantaRay',
    lat: 27.40,
    lng: -82.70,
    minZoom: 12,
    maxZoom: 18,
    size: [24, 18],
    title: 'Manta Ray!',
    fact: 'Spotted eagle rays and mantas frequent the warm Gulf waters near Longboat Key. Their graceful underwater "flight" makes them a favorite sight for divers and snorkelers.',
    svgKey: 'mantaRay',
    animCategory: 'water',
  },
  {
    id: 'spanishMoss',
    lat: 28.00,
    lng: -82.44,
    minZoom: 14,
    maxZoom: 18,
    size: [16, 22],
    title: 'Spanish Moss!',
    fact: "Spanish moss isn't moss at all — it's an epiphyte related to pineapples. Draped on every live oak in old Seminole Heights, it defines the Gothic beauty of Florida's tree canopy.",
    svgKey: 'spanishMoss',
    animCategory: 'culture',
  },
];
