// Icon batch definitions for the Icon Workshop
// Category colors from the spec
export const CATEGORY_COLORS = {
  water:    '#2DD4BF',
  bird:     '#38BDF8',
  land:     '#4ADE80',
  food:     '#FB923C',
  culture:  '#A78BFA',
  sport:    '#F87171',
  spooky:   '#C084FC',
  landmark: '#FBBF24',
};

// Easter egg icon specs (50 icons)
export const EASTER_EGG_SPECS = [
  { svgKey: 'pirateShip', viewBox: '0 0 32 22', size: [48, 33], category: 'culture', batch: 1, description: 'José Gaspar\'s pirate ship — the legendary pirate said to have roamed Tampa Bay, celebrated every year at Gasparilla' },
  { svgKey: 'kraken', viewBox: '0 0 34 24', size: [56, 40], category: 'water', batch: 1, description: 'A giant kraken rising from Tampa Bay — sea monster folklore tied to the deep Gulf waters' },
  { svgKey: 'skunkApe', viewBox: '0 0 18 24', size: [28, 38], category: 'land', batch: 1, description: 'Florida\'s Skunk Ape — the swamp-dwelling Bigfoot cousin rumored to lurk in the Everglades and Green Swamp' },
  { svgKey: 'strawberry', viewBox: '0 0 16 20', size: [26, 32], category: 'food', batch: 1, description: 'Plant City strawberry — the Winter Strawberry Capital of the World, home of the annual Strawberry Festival' },
  { svgKey: 'lightning', viewBox: '0 0 20 28', size: [30, 42], category: 'culture', batch: 1, description: 'Lightning bolt over Lightning Alley — Tampa Bay is the lightning capital of North America' },
  { svgKey: 'mermaid', viewBox: '0 0 18 24', size: [28, 38], category: 'culture', batch: 2, description: 'Weeki Wachee mermaid — the iconic live mermaid shows at Weeki Wachee Springs, running since 1947' },
  { svgKey: 'cigar', viewBox: '0 0 28 12', size: [42, 18], category: 'food', batch: 2, description: 'Hand-rolled Ybor City cigar — Tampa was once the Cigar Capital of the World with 200+ factories' },
  { svgKey: 'dolphin', viewBox: '0 0 24 16', size: [38, 26], category: 'water', batch: 2, description: 'Bottlenose dolphin leaping — commonly spotted playing in Tampa Bay and along the Gulf Coast' },
  { svgKey: 'pelican', viewBox: '0 0 18 22', size: [28, 34], category: 'bird', batch: 2, description: 'Brown pelican diving — an iconic coastal bird seen on every pier and dock around the Bay' },
  { svgKey: 'osprey', viewBox: '0 0 22 22', size: [34, 34], category: 'bird', batch: 2, description: 'Osprey in flight — fish hawks that nest on power poles and channel markers all around Tampa Bay' },
  { svgKey: 'sandhillCrane', viewBox: '0 0 18 24', size: [28, 38], category: 'bird', batch: 3, description: 'Sandhill crane pair — tall gray birds that wander suburban lawns and golf courses across Central Florida' },
  { svgKey: 'gopherTortoise', viewBox: '0 0 20 16', size: [32, 26], category: 'land', batch: 3, description: 'Gopher tortoise — a keystone species whose burrows shelter 350+ other animals in Florida scrub habitat' },
  { svgKey: 'alligator', viewBox: '-1 -1 28 24', size: [44, 36], category: 'land', batch: 3, description: 'American alligator — 1.3 million gators call Florida home, often found in retention ponds and golf course lakes' },
  { svgKey: 'roseateSpoonbill', viewBox: '0 0 20 22', size: [32, 34], category: 'bird', batch: 3, description: 'Roseate spoonbill wading — the stunning pink bird often mistaken for a flamingo in Tampa Bay mangroves' },
  { svgKey: 'seaTurtle', viewBox: '0 0 22 18', size: [34, 28], category: 'water', batch: 3, description: 'Loggerhead sea turtle — nests on Gulf beaches every summer, protected by lights-out ordinances' },
  { svgKey: 'skywayBridge', viewBox: '0 0 30 16', size: [48, 26], category: 'landmark', batch: 4, description: 'Sunshine Skyway Bridge — the iconic cable-stayed bridge spanning Tampa Bay, rebuilt after the 1980 disaster' },
  { svgKey: 'spongeDiver', viewBox: '0 0 16 24', size: [26, 38], category: 'water', batch: 4, description: 'Tarpon Springs sponge diver — Greek immigrants brought deep-sea sponge diving to Florida in the early 1900s' },
  { svgKey: 'hockeyPuck', viewBox: '0 0 16 16', size: [22, 22], category: 'sport', batch: 4, description: 'Hockey puck — for the Tampa Bay Lightning, back-to-back Stanley Cup champions in 2020 and 2021' },
  { svgKey: 'pirateFlag', viewBox: '0 0 20 14', size: [28, 22], category: 'sport', batch: 4, description: 'Jolly Roger pirate flag — representing the Tampa Bay Buccaneers, Super Bowl LV champions' },
  { svgKey: 'stingray', viewBox: '0 0 24 18', size: [32, 28], category: 'water', batch: 4, description: 'Stingray gliding — cownose rays migrate through Tampa Bay in massive schools every spring' },
  { svgKey: 'greekCross', viewBox: '0 0 16 16', size: [26, 26], category: 'culture', batch: 5, description: 'Greek Orthodox cross — honoring Tarpon Springs\' Greek heritage and the annual Epiphany cross dive' },
  { svgKey: 'cubanSandwich', viewBox: '0 0 24 12', size: [38, 20], category: 'food', batch: 5, description: 'Cuban sandwich — Tampa\'s signature pressed sandwich with ham, roast pork, Swiss, pickles, and mustard on Cuban bread' },
  { svgKey: 'grouper', viewBox: '0 0 22 14', size: [34, 22], category: 'food', batch: 5, description: 'Grouper fish — the Gulf grouper sandwich is a Tampa Bay culinary staple found at every waterfront restaurant' },
  { svgKey: 'orange', viewBox: '0 0 16 16', size: [26, 26], category: 'food', batch: 5, description: 'Florida orange — the Sunshine State produces 70% of U.S. citrus, with groves dotting the Tampa Bay region' },
  { svgKey: 'craftBeer', viewBox: '0 0 14 18', size: [22, 28], category: 'food', batch: 5, description: 'Craft beer pint — Tampa Bay has 80+ craft breweries, earning it recognition as a top beer destination' },
  { svgKey: 'flamingo', viewBox: '0 0 14 22', size: [22, 34], category: 'bird', batch: 6, description: 'Pink flamingo — wild flamingos are returning to Florida after a century of absence, spotted in Tampa Bay' },
  { svgKey: 'tikiHut', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 6, description: 'Tiki hut — the quintessential Florida beach bar, thatched chickee huts line waterfront spots around the Bay' },
  { svgKey: 'ufo', viewBox: '0 0 22 14', size: [34, 22], category: 'spooky', batch: 6, description: 'UFO over Gulf Breeze — Florida\'s famous 1987 UFO sighting wave, one of the most documented in history' },
  { svgKey: 'conchShell', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 6, description: 'Queen conch shell — a symbol of Florida\'s coastal heritage, once abundant in Gulf waters' },
  { svgKey: 'treasureChest', viewBox: '0 0 18 16', size: [28, 26], category: 'culture', batch: 6, description: 'Pirate treasure chest — legends of buried treasure along the Gulf Coast tied to Gasparilla and other pirates' },
  { svgKey: 'gibsonton', viewBox: '0 0 20 18', size: [32, 28], category: 'spooky', batch: 7, description: 'Gibsonton carnival tent — "Gibtown" was the off-season home for sideshow performers, with special zoning for exotic animals' },
  { svgKey: 'spookHill', viewBox: '0 0 20 14', size: [28, 22], category: 'spooky', batch: 7, description: 'Spook Hill gravity illusion — the famous optical illusion hill in Lake Wales where cars appear to roll uphill' },
  { svgKey: 'joyland', viewBox: '0 0 20 20', size: [32, 32], category: 'spooky', batch: 7, description: 'Abandoned Joyland ferris wheel — haunting remnants of Florida\'s forgotten roadside amusement parks' },
  { svgKey: 'babeRuth', viewBox: '0 0 16 16', size: [26, 26], category: 'sport', batch: 7, description: 'Babe Ruth baseball — the Sultan of Swat did spring training in Tampa, hitting his longest home run at Plant Field' },
  { svgKey: 'phosphateMining', viewBox: '0 0 20 16', size: [32, 26], category: 'culture', batch: 7, description: 'Phosphate mining cart — Bone Valley near Tampa produces 75% of U.S. phosphate, with fossil-rich deposits' },
  { svgKey: 'sharkTooth', viewBox: '0 0 14 18', size: [22, 28], category: 'water', batch: 8, description: 'Megalodon shark tooth — Venice, FL is the "Shark Tooth Capital of the World" with prehistoric fossils washing ashore' },
  { svgKey: 'tarponFish', viewBox: '0 0 24 16', size: [38, 26], category: 'water', batch: 8, description: 'Silver king tarpon — the prized game fish that draws anglers to Tampa Bay bridges and passes every summer' },
  { svgKey: 'shipwreck', viewBox: '0 0 24 16', size: [38, 26], category: 'spooky', batch: 8, description: 'Sunken shipwreck — hundreds of wrecks lie off the Gulf Coast, from Spanish galleons to WWII vessels' },
  { svgKey: 'mantaRay', viewBox: '0 0 24 18', size: [38, 28], category: 'water', batch: 8, description: 'Giant manta ray — graceful winged rays spotted in Gulf waters, with wingspans up to 23 feet' },
  { svgKey: 'spanishMoss', viewBox: '0 0 16 22', size: [26, 34], category: 'culture', batch: 8, description: 'Spanish moss draping — the atmospheric gray garlands hanging from live oaks throughout the Bay area' },
  { svgKey: 'greenFlash', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 9, description: 'Green flash sunset — the rare optical phenomenon visible over the Gulf of Mexico at sunset' },
  { svgKey: 'unconquered', viewBox: '0 0 18 22', size: [28, 34], category: 'culture', batch: 9, description: 'Seminole spear — honoring the unconquered Seminole Tribe of Florida, the only tribe never to sign a peace treaty' },
  { svgKey: 'mangroveTunnels', viewBox: '0 0 22 16', size: [34, 26], category: 'water', batch: 9, description: 'Mangrove tunnel kayak trail — paddling through arching red mangrove canopies in Weedon Island and Terra Ceia' },
  { svgKey: 'kerouac', viewBox: '0 0 16 18', size: [26, 28], category: 'culture', batch: 9, description: 'Jack Kerouac\'s typewriter — the Beat Generation author wrote "The Dharma Bums" while living in St. Petersburg' },
  { svgKey: 'bioluminescence', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 9, description: 'Bioluminescent bay glow — dinoflagellates light up Tampa Bay waters with ethereal blue-green light on warm nights' },
  { svgKey: 'floridaMan', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 10, description: 'Florida Man — the beloved internet meme born from Florida\'s public records laws and wild news headlines' },
  { svgKey: 'hurricaneAlley', viewBox: '0 0 22 18', size: [34, 28], category: 'water', batch: 10, description: 'Hurricane spiral — Tampa Bay sits in Hurricane Alley, though it hasn\'t taken a direct major hit since 1921' },
  { svgKey: 'redTide', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 10, description: 'Red tide algae bloom — Karenia brevis blooms that periodically affect Gulf beaches, a natural but disruptive phenomenon' },
  { svgKey: 'honeymoonIsland', viewBox: '0 0 22 16', size: [34, 26], category: 'culture', batch: 10, description: 'Honeymoon Island palm — the state park was a 1940s honeymoon resort, now one of Florida\'s most-visited parks' },
  { svgKey: 'ghostOrchid', viewBox: '0 0 16 20', size: [26, 32], category: 'land', batch: 10, description: 'Ghost orchid in bloom — the rare, ethereal flower made famous by "The Orchid Thief," found in Florida swamps' },
];

// Best of the Bay icon specs (12 icons)
export const BEST_OF_BAY_SPECS = [
  { svgKey: 'bernsSteak', destination: "Bern's Steak House", batch: 11, description: 'Sizzling steak — Bern\'s legendary steakhouse with its wine cellar and dessert room, a Tampa institution since 1956' },
  { svgKey: 'flamencoDancer', destination: 'Columbia Restaurant', batch: 11, description: 'Flamenco dancer — Columbia Restaurant in Ybor City, Florida\'s oldest restaurant (1905) with nightly flamenco shows' },
  { svgKey: 'pirateShipBow', destination: 'Raymond James Stadium', batch: 11, description: 'Pirate ship bow — the 103-foot replica pirate ship inside Raymond James Stadium that fires cannons after Bucs touchdowns' },
  { svgKey: 'lightningBolt', destination: 'Amalie Arena', batch: 11, description: 'Lightning bolt strike — home of the Tampa Bay Lightning at Amalie Arena on the downtown waterfront' },
  { svgKey: 'meltingClock', destination: 'The Dali Museum', batch: 11, description: 'Dalí melting clock — The Dalí Museum in St. Pete houses the largest collection of Salvador Dalí works outside Spain' },
  { svgKey: 'cigarIcon', destination: 'Ybor City', batch: 11, description: 'Cigar and brick — Ybor City\'s historic cigar district with its brick streets, wrought iron, and roaming chickens' },
  { svgKey: 'bridgeArch', destination: 'Tampa Riverwalk', batch: 11, description: 'Bridge arch over river — the 2.6-mile Tampa Riverwalk connecting downtown\'s parks, museums, and waterfront dining' },
  { svgKey: 'ringlingCircus', destination: 'The Ringling', batch: 11, description: 'Circus tent — The Ringling Museum in Sarasota, John Ringling\'s legacy with art, circus memorabilia, and Ca\' d\'Zan mansion' },
  { svgKey: 'beachUmbrella', destination: 'Clearwater Beach', batch: 11, description: 'Beach umbrella — Clearwater Beach, consistently ranked America\'s #1 beach for its sugar-white sand and clear water' },
  { svgKey: 'palmTree', destination: 'Siesta Key Beach', batch: 11, description: 'Palm tree on white sand — Siesta Key\'s 99% pure quartz crystal sand that stays cool even in summer heat' },
  { svgKey: 'guitarSilhouette', destination: 'Seminole Hard Rock', batch: 11, description: 'Guitar silhouette — Seminole Hard Rock Hotel & Casino, the guitar-shaped landmark visible for miles' },
  { svgKey: 'donCesar', destination: 'The Don CeSar', batch: 11, description: 'Pink palace towers — The Don CeSar, the iconic 1928 pink resort on St. Pete Beach known as the "Pink Palace"' },
];

// Total icons: 50 easter eggs * 2 states + 12 best of bay = 112
export const TOTAL_ICONS = 112;

export const BATCH_NAMES = {
  1: 'Batch 1: Warm-up',
  2: 'Batch 2: Sea & Sky',
  3: 'Batch 3: Wildlife',
  4: 'Batch 4: Landmarks',
  5: 'Batch 5: Food & Culture',
  6: 'Batch 6: Tropical',
  7: 'Batch 7: Spooky & Sport',
  8: 'Batch 8: Deep Water',
  9: 'Batch 9: Folklore',
  10: 'Batch 10: Florida Icons',
  11: 'Batch 11: Best of the Bay',
};
