// Icon batch definitions for the Icon Workshop
// Category colors from the spec
export const CATEGORY_COLORS = {
  water:    '#2DD4BF',
  bird:     '#38BDF8',
  land:     '#4ADE80',
  food:     '#FB923C',
  culture:  '#A78BFA',
  sport:    '#F87171',
  spooky:   '#C084FC',
  landmark: '#FBBF24',
};

// Easter egg icon specs (50 icons)
export const EASTER_EGG_SPECS = [
  { svgKey: 'pirateShip', viewBox: '0 0 28 20', size: [42, 30], category: 'culture', batch: 1 },
  { svgKey: 'kraken', viewBox: '0 0 32 22', size: [54, 38], category: 'water', batch: 1 },
  { svgKey: 'skunkApe', viewBox: '0 0 18 24', size: [28, 38], category: 'land', batch: 1 },
  { svgKey: 'strawberry', viewBox: '0 0 16 20', size: [26, 32], category: 'food', batch: 1 },
  { svgKey: 'lightning', viewBox: '0 0 14 24', size: [22, 38], category: 'culture', batch: 1 },
  { svgKey: 'mermaid', viewBox: '0 0 18 24', size: [28, 38], category: 'culture', batch: 2 },
  { svgKey: 'cigar', viewBox: '0 0 28 10', size: [42, 16], category: 'food', batch: 2 },
  { svgKey: 'dolphin', viewBox: '0 0 24 16', size: [38, 26], category: 'water', batch: 2 },
  { svgKey: 'pelican', viewBox: '0 0 18 22', size: [28, 34], category: 'bird', batch: 2 },
  { svgKey: 'osprey', viewBox: '0 0 22 22', size: [34, 34], category: 'bird', batch: 2 },
  { svgKey: 'sandhillCrane', viewBox: '0 0 18 24', size: [28, 38], category: 'bird', batch: 3 },
  { svgKey: 'gopherTortoise', viewBox: '0 0 20 16', size: [32, 26], category: 'land', batch: 3 },
  { svgKey: 'alligator', viewBox: '0 0 26 14', size: [40, 22], category: 'land', batch: 3 },
  { svgKey: 'roseateSpoonbill', viewBox: '0 0 20 22', size: [32, 34], category: 'bird', batch: 3 },
  { svgKey: 'seaTurtle', viewBox: '0 0 22 18', size: [34, 28], category: 'water', batch: 3 },
  { svgKey: 'skywayBridge', viewBox: '0 0 30 16', size: [48, 26], category: 'landmark', batch: 4 },
  { svgKey: 'spongeDiver', viewBox: '0 0 16 24', size: [26, 38], category: 'water', batch: 4 },
  { svgKey: 'hockeyPuck', viewBox: '0 0 16 16', size: [22, 22], category: 'sport', batch: 4 },
  { svgKey: 'pirateFlag', viewBox: '0 0 20 14', size: [28, 22], category: 'sport', batch: 4 },
  { svgKey: 'stingray', viewBox: '0 0 24 18', size: [32, 28], category: 'water', batch: 4 },
  { svgKey: 'greekCross', viewBox: '0 0 16 16', size: [26, 26], category: 'culture', batch: 5 },
  { svgKey: 'cubanSandwich', viewBox: '0 0 24 12', size: [38, 20], category: 'food', batch: 5 },
  { svgKey: 'grouper', viewBox: '0 0 22 14', size: [34, 22], category: 'food', batch: 5 },
  { svgKey: 'orange', viewBox: '0 0 16 16', size: [26, 26], category: 'food', batch: 5 },
  { svgKey: 'craftBeer', viewBox: '0 0 14 18', size: [22, 28], category: 'food', batch: 5 },
  { svgKey: 'flamingo', viewBox: '0 0 14 22', size: [22, 34], category: 'bird', batch: 6 },
  { svgKey: 'tikiHut', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 6 },
  { svgKey: 'ufo', viewBox: '0 0 22 14', size: [34, 22], category: 'spooky', batch: 6 },
  { svgKey: 'conchShell', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 6 },
  { svgKey: 'treasureChest', viewBox: '0 0 18 16', size: [28, 26], category: 'culture', batch: 6 },
  { svgKey: 'gibsonton', viewBox: '0 0 20 18', size: [32, 28], category: 'spooky', batch: 7 },
  { svgKey: 'spookHill', viewBox: '0 0 20 14', size: [28, 22], category: 'spooky', batch: 7 },
  { svgKey: 'joyland', viewBox: '0 0 20 20', size: [32, 32], category: 'spooky', batch: 7 },
  { svgKey: 'babeRuth', viewBox: '0 0 16 16', size: [26, 26], category: 'sport', batch: 7 },
  { svgKey: 'phosphateMining', viewBox: '0 0 20 16', size: [32, 26], category: 'culture', batch: 7 },
  { svgKey: 'sharkTooth', viewBox: '0 0 14 18', size: [22, 28], category: 'water', batch: 8 },
  { svgKey: 'tarponFish', viewBox: '0 0 24 16', size: [38, 26], category: 'water', batch: 8 },
  { svgKey: 'shipwreck', viewBox: '0 0 24 16', size: [38, 26], category: 'spooky', batch: 8 },
  { svgKey: 'mantaRay', viewBox: '0 0 24 18', size: [38, 28], category: 'water', batch: 8 },
  { svgKey: 'spanishMoss', viewBox: '0 0 16 22', size: [26, 34], category: 'culture', batch: 8 },
  { svgKey: 'greenFlash', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 9 },
  { svgKey: 'unconquered', viewBox: '0 0 18 22', size: [28, 34], category: 'culture', batch: 9 },
  { svgKey: 'mangroveTunnels', viewBox: '0 0 22 16', size: [34, 26], category: 'water', batch: 9 },
  { svgKey: 'kerouac', viewBox: '0 0 16 18', size: [26, 28], category: 'culture', batch: 9 },
  { svgKey: 'bioluminescence', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 9 },
  { svgKey: 'floridaMan', viewBox: '0 0 18 18', size: [28, 28], category: 'culture', batch: 10 },
  { svgKey: 'hurricaneAlley', viewBox: '0 0 22 18', size: [34, 28], category: 'water', batch: 10 },
  { svgKey: 'redTide', viewBox: '0 0 20 14', size: [32, 22], category: 'water', batch: 10 },
  { svgKey: 'honeymoonIsland', viewBox: '0 0 22 16', size: [34, 26], category: 'culture', batch: 10 },
  { svgKey: 'ghostOrchid', viewBox: '0 0 16 20', size: [26, 32], category: 'land', batch: 10 },
];

// Best of the Bay icon specs (12 icons)
export const BEST_OF_BAY_SPECS = [
  { svgKey: 'bernsSteak', destination: "Bern's Steak House", batch: 11 },
  { svgKey: 'flamencoDancer', destination: 'Columbia Restaurant', batch: 11 },
  { svgKey: 'pirateShipBow', destination: 'Raymond James Stadium', batch: 11 },
  { svgKey: 'lightningBolt', destination: 'Amalie Arena', batch: 11 },
  { svgKey: 'meltingClock', destination: 'The Dali Museum', batch: 11 },
  { svgKey: 'cigarIcon', destination: 'Ybor City', batch: 11 },
  { svgKey: 'bridgeArch', destination: 'Tampa Riverwalk', batch: 11 },
  { svgKey: 'ringlingCircus', destination: 'The Ringling', batch: 11 },
  { svgKey: 'beachUmbrella', destination: 'Clearwater Beach', batch: 11 },
  { svgKey: 'palmTree', destination: 'Siesta Key Beach', batch: 11 },
  { svgKey: 'guitarSilhouette', destination: 'Seminole Hard Rock', batch: 11 },
  { svgKey: 'donCesar', destination: 'The Don CeSar', batch: 11 },
];

// Total icons: 50 easter eggs * 2 states + 12 best of bay = 112
export const TOTAL_ICONS = 112;

export const BATCH_NAMES = {
  1: 'Batch 1: Warm-up',
  2: 'Batch 2: Sea & Sky',
  3: 'Batch 3: Wildlife',
  4: 'Batch 4: Landmarks',
  5: 'Batch 5: Food & Culture',
  6: 'Batch 6: Tropical',
  7: 'Batch 7: Spooky & Sport',
  8: 'Batch 8: Deep Water',
  9: 'Batch 9: Folklore',
  10: 'Batch 10: Florida Icons',
  11: 'Batch 11: Best of the Bay',
};
